### ISSUE TITLE
Backend logic fixing for Tutors, Single Tutor and Tutor Jobs Page

### ISSUE THREAD

**Issue by shamiul-anik** [shamiul-anik/edu-mentor#1]
**To be Fix:**
1. Only admin verified tutors can be seen in **Tutors** page.
2. Single tutor page will only show admin verified tuitions added by a tutor from his dashboard.
3. Tutor Jobs will only show admin verified tutor jobs.

**Comment by SAIDUR-WAY** [comment]
data show isVerified id done.. bug fixed.
